name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --prefer-source --no-interaction
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
  push-to-codecov:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
    - name: Push to codecov
      run: bash <(curl -s https://codecov.io/bash)
